[package]
name = "codegen"
version = "0.1.1"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2021"

[dependencies]
phf_codegen = "0.13"
regex = "1.0"
marksman_escape = "0.1"
linked-hash-map = "0.5"
